version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
  heroku_deploy_review_app:
    executor: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          api-key: $HEROKU_API_KEY

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
